writer1          = console
writer1.format   = {date: yyyy-MM-dd HH:mm:ss.SSS} {level}: {message}{exception}

writer2          = rolling file
writer2.level    = info
writer2.format   = {date: yyyy-MM-dd HH:mm:ss.SSS} {level}: {message}{exception}
writer2.file     = /log/log_{pid}_{count}.txt
writer2.charset  = UTF-8
writer2.policies = startup, daily: 03:00
writer2.backups  = 30
writer2.convert  = gzip
